---

name: dond-test

on:
  push:
    branches:
      - master

jobs:
  dond-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: echo test
        run: echo "test"
      - name: echo pwd
        run: pwd
      - name: file
        run: ls -la
      - name: docker image test
        run: docker image ls
#       - name: docker pull test
#         run: docker pull docker
      - name: docker pull test2
        run: docker pull archlinux
      - name: docker image test
        run: docker image ls
#       - name: dond test
#         run: docker run -v /var/run/docker.sock:/var/run/docker.sock docker ls -l
      - name: dond test
        run: docker run -v /var/run/docker.sock:/var/run/docker.sock docker pwd
      - name: dond test2
        run: docker run -v /var/run/docker.sock:/var/run/docker.sock -v /home/runner/work/dondtest/dondtest/test.sh:/home/runner/test.sh archlinux ./test.sh
      - name: dond docker test
        run: docker ps -a

