---

name: dond-test

on:
  push:
    branches:
      - master

jobs:
  dond-test:
    runs-on: ubuntu-latest
    steps:
      - name: echo test
        run: echo "test"
      - name: docker image test
        run: docker image ls
#       - name: docker pull test
#         run: docker pull docker
      - name: docker pull test2
        run: docker pull archlinux
      - name: docker image test
        run: docker image ls
#       - name: dond test
#         run: docker run -v /var/run/docker.sock:/var/run/docker.sock docker ls -l
      - name: dond test2
        run: docker run -v /var/run/docker.sock:/var/run/docker.sock archlinux ls -l
      - name: dond test3
        run: docker run -v /var/run/docker.sock:/var/run/docker.sock archlinux pacman -S python
      - name: dond docker test
        run: docker ps -a

